@startuml

title UML-діаграма розгортання ПП

left to right direction

skinparam componentStyle uml1

node "<<Smartphone>>" as smrtphn1 {
	node "<<OS Android>>" {
		component [.apk (Android studio)]
	}
}

interface "Сенсорний екран"

(Сенсорний екран) -- smrtphn1

node "<<Server #1>>" as serv1 {
	node "<<OS Linux>>" {
		node "<<Application Server Apache Tomcat>>" {
			component [.jar (IntelliJ IDEA)]
		}
	}
}

smrtphn1 -- serv1

node "<<Server #2>>" as serv2 {
	node "<<OS  Linux>>" {
		node "<<Database Server PostgreSQL>>" {
			database "Relation Database"
		}
	}
}

serv1 -- serv2

@enduml
