name: Test Cases Modified
on:
  push:
    branches: main

jobs:
  TestCasesModified:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: "actions/checkout@v3"
      
      - name: Compile & Execute
        run: |
          cd $GITHUB_WORKSPACE/
          java TestCasesModified.java